### ISSUE TITLE
add resources for new contributors

### ISSUE THREAD

**Issue by deniss-eh** [deniss-eh/hacktuber#1]
you can add resources for new contributors here and help me by contributing to this repository :)

**Comment by SalmaanShire365** [comment]
Hello @deniss-eh, I am interested in contributing to this. 
Could I be assigned to this issue?

**Comment by HPatel08** [comment]
Please Merge my PR #10

**Comment by deniss-eh** [comment]
@SalmaanShire365 ya sure 😃

**Comment by deniss-eh** [comment]
@SalmaanShire365 @HPatel08 You can also contribute to my new repository where you can contribute by opening pull requests for DSA related programs. :)
https://github.com/deniss-eh/DSA-HACKTOBERFEST
