### ISSUE TITLE
Add programs related to DSA problems

### ISSUE THREAD

**Issue by deniss-eh** [deniss-eh/hacktuber#11]
edit : make sure you guys add programs in program/c++ folder if having c++ program else create new folder according to the language.

**Comment by destroyer5067** [comment]
@deniss-eh Hey can you elaborate what we need to do in this issue?

**Comment by deniss-eh** [comment]
Just need to commit new program files related to data structures and algorithms. You can use any language.

**Comment by deniss-eh** [comment]
make sure you guys add programs in program/c++ folder

**Comment by ShreyaShukla03** [comment]
Please check PR #14

**Comment by deniss-eh** [comment]
> Please check PR #14

Checked and merged !!

**Comment by akashbiswas0** [comment]
@deniss-eh pls assign it to me

**Comment by deniss-eh** [comment]
@AkashB2208 

> @deniss-eh pls assign it to me

Brother its open for all.. you can contribute.. but i recommend you to contribute there https://github.com/deniss-eh/DSA-HACKTOBERFEST

**Comment by deniss-eh** [comment]
@destroyer5067 @ShreyaShukla03 @AkashB2208 You can also contribute to my new repository where you can contribute by opening pull requests for DSA related programs. :)
https://github.com/deniss-eh/DSA-HACKTOBERFEST
