### ISSUE TITLE
Update documentations

### ISSUE THREAD

**Issue by deniss-eh** [deniss-eh/hacktuber#8]
update documentations according to hacktoberfest.
documentation includes files like README.md , CODE_OF_CONDUCT.md , CONTRIBUTING.md , etc.
make sure to add this issue link to your pull request when opening a pull request for this issue

**Comment by Anubhakri13** [comment]
Hii @deniss-eh ,May you assign this to me?

**Comment by deniss-eh** [comment]
Sure

**Comment by deniss-eh** [comment]
@Anubhakri13 You can also contribute to my new repository where you can contribute by opening pull requests for DSA related programs. :)
https://github.com/deniss-eh/DSA-HACKTOBERFEST
